nss-ecm: avoid duplicating enteries in /etc/sysctl.d/99-qca-nss-ecm.conf

diff --git a/qca-nss-ecm/files/qca-nss-ecm.init b/qca-nss-ecm/files/qca-nss-ecm.init
--- a/qca-nss-ecm/files/qca-nss-ecm.init
+++ b/qca-nss-ecm/files/qca-nss-ecm.init
@@ -21,98 +21,99 @@
 START=19
 
 get_front_end_mode() {
-	config_load "ecm"
-	config_get front_end global acceleration_engine "nss"
+  config_load "ecm"
+  config_get front_end global acceleration_engine "nss"
 
-	case $front_end in
-	auto)
-		echo '0'
-		;;
-	nss)
-		echo '1'
-		;;
-	sfe)
-		echo '2'
-		;;
-	*)
-		echo 'uci_option_acceleration_engine is invalid'
-	esac
+  case $front_end in
+    auto)
+      echo 0
+      ;;
+    nss)
+      echo 1
+      ;;
+    sfe)
+      echo 2
+      ;;
+    *)
+      echo "uci_option_acceleration_engine is invalid"
+      ;;
+  esac
 }
 
 support_bridge() {
-	#NSS support bridge acceleration
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && return 0
-	#SFE doesn't support bridge acceleration
-	[ -d /sys/kernel/debug/ecm/ecm_sfe_ipv4 ] && return 1
+  #NSS support bridge acceleration
+  [ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && return 0
+  #SFE doesn't support bridge acceleration
+  [ -d /sys/kernel/debug/ecm/ecm_sfe_ipv4 ] && return 1
 }
 
 load_sfe() {
-	[ -d /sys/module/shortcut_fe ] || insmod shortcut-fe
-	[ -d /sys/module/shortcut_fe_ipv6 ] || insmod shortcut-fe-ipv6
-	[ -d /sys/module/shortcut_fe_drv ] || insmod shortcut-fe-drv
+  [ -d /sys/module/shortcut_fe ] || insmod shortcut-fe
+  [ -d /sys/module/shortcut_fe_ipv6 ] || insmod shortcut-fe-ipv6
+  [ -d /sys/module/shortcut_fe_drv ] || insmod shortcut-fe-drv
 }
 
 load_ecm() {
-	[ -d /sys/module/ecm ] || {
-		insmod ecm front_end_selection=$(get_front_end_mode)
-        echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
-	}
+  [ -d /sys/module/ecm ] || {
+    insmod ecm front_end_selection="$(get_front_end_mode)"
+    echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
+  }
 
-	support_bridge && {
-		sysctl -w net.bridge.bridge-nf-call-ip6tables=1
-		sysctl -w net.bridge.bridge-nf-call-iptables=1
-	}
+  support_bridge && {
+    sysctl -w net.bridge.bridge-nf-call-ip6tables=1
+    sysctl -w net.bridge.bridge-nf-call-iptables=1
+  }
 }
 
 unload_ecm() {
-	sysctl -w net.bridge.bridge-nf-call-ip6tables=0
-	sysctl -w net.bridge.bridge-nf-call-iptables=0
+  sysctl -w net.bridge.bridge-nf-call-ip6tables=0
+  sysctl -w net.bridge.bridge-nf-call-iptables=0
 
-	if [ -d /sys/module/ecm ]; then
-		#
-		# Stop ECM frontends
-		#
-		echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
-		echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
+  if [ -d /sys/module/ecm ]; then
+    #
+    # Stop ECM frontends
+    #
+    echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
+    echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
 
-		#
-		# Defunct the connections
-		#
-	        echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
-		sleep 5;
+    #
+    # Defunct the connections
+    #
+    echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
+    sleep 5
 
-		rmmod ecm
-		sleep 1
-	fi
+    rmmod ecm
+    sleep 1
+  fi
 }
 
 start() {
-	load_ecm
+  load_ecm
 
-	# If the acceleration engine is NSS, enable wifi redirect.
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=1
+  # If the acceleration engine is NSS, enable wifi redirect.
+  [ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=1
 
-	support_bridge && {
-		echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/99-qca-nss-ecm.conf
-		echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/99-qca-nss-ecm.conf
-	}
+  support_bridge && {
+    sed -i '/^net.bridge.bridge-nf-call-ip/d' /etc/sysctl.d/99-qca-nss-ecm.conf
+    echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/99-qca-nss-ecm.conf
+    echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/99-qca-nss-ecm.conf
+  }
 
-	if [ -d /sys/module/qca_ovsmgr ]; then
-		insmod ecm_ovs
-	fi
+  if [ -d /sys/module/qca_ovsmgr ]; then
+    insmod ecm_ovs
+  fi
 
 }
 
 stop() {
-	# If the acceleration engine is NSS, disable wifi redirect.
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=0
+  # If the acceleration engine is NSS, disable wifi redirect.
+  [ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=0
 
-	sed '/net.bridge.bridge-nf-call-ip6tables=1/d' -i /etc/sysctl.d/99-qca-nss-ecm.conf
-	sed '/net.bridge.bridge-nf-call-iptables=1/d' -i /etc/sysctl.d/99-qca-nss-ecm.conf
+  sed -i '/^net.bridge.bridge-nf-call-ip/d' /etc/sysctl.d/99-qca-nss-ecm.conf
 
-	if [ -d /sys/module/ecm_ovs ]; then
-		rmmod ecm_ovs
-	fi
+  if [ -d /sys/module/ecm_ovs ]; then
+    rmmod ecm_ovs
+  fi
 
-	unload_ecm
+  unload_ecm
 }
