qca-nss-ecm: properly setup firewall, init, defaults for 6.1

diff --git a/qca/qca-nss-ecm/files/qca-nss-ecm.init b/qca/qca-nss-ecm/files/qca-nss-ecm.init
--- a/qca/qca-nss-ecm/files/qca-nss-ecm.init
+++ b/qca/qca-nss-ecm/files/qca-nss-ecm.init
@@ -18,116 +18,121 @@
 # openwrt build scripts automatically enable this package starting
 # at boot.
 
-START=19
+START=26
 
-get_front_end_mode() {
-	config_load "ecm"
-	config_get front_end global acceleration_engine "auto"
-
-	case $front_end in
-	auto)
-		echo '0'
-		;;
-	nss)
-		echo '1'
-		;;
-	*)
-		echo 'uci_option_acceleration_engine is invalid'
-	esac
+sysctl_update() {
+  local name value file
+  name=${1//\//\\/}
+  value=${2//\//\\/}
+  file=${3:-/etc/sysctl.d/qca-nss-ecm.conf}
+  sed -i -e '/^#\?\(\s*'"${name}"'\s*=\s*\).*/{s//\1'"${value}"'/;:a;n;ba;q}' \
+    -e '$a'"${name}"'='"${value}" "${file}"
+  sysctl -w ${name}=${value}
 }
 
-support_bridge() {
-	# NSS support bridge acceleration
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && [ -d /sys/kernel/debug/ecm/ecm_nss_ipv6 ] && return 0
+get_front_end_mode() {
+  config_load "ecm"
+  config_get front_end global acceleration_engine "auto"
+
+  case $front_end in
+    auto)
+      echo '0'
+      ;;
+    nss)
+      echo '1'
+      ;;
+    *)
+      echo 'uci_option_acceleration_engine is invalid'
+  esac
 }
 
 enable_bridge_filtering() {
-	sysctl -w net.bridge.bridge-nf-call-arptables=1
-	sysctl -w net.bridge.bridge-nf-call-iptables=1
-	sysctl -w net.bridge.bridge-nf-call-ip6tables=1
-
-	if ([ -z "$(grep "net.bridge.bridge-nf-call-arptables=1" /etc/sysctl.d/qca-nss-ecm.conf)" ] && \
-		[ -z "$(grep "net.bridge.bridge-nf-call-iptables=1" /etc/sysctl.d/qca-nss-ecm.conf)" ] && \
-		[ -z "$(grep "net.bridge.bridge-nf-call-ip6tables=1" /etc/sysctl.d/qca-nss-ecm.conf)" ] \
-	); then
-		echo 'net.bridge.bridge-nf-call-arptables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
-		echo 'net.bridge.bridge-nf-call-iptables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
-		echo 'net.bridge.bridge-nf-call-ip6tables=1' >> /etc/sysctl.d/qca-nss-ecm.conf
-	fi
+  sysctl_update net.bridge.bridge-nf-call-arptables 1
+  sysctl_update net.bridge.bridge-nf-call-iptables 1
+  sysctl_update net.bridge.bridge-nf-call-ip6tables 1
 }
 
 disable_bridge_filtering() {
-	sysctl -w net.bridge.bridge-nf-call-arptables=0
-	sysctl -w net.bridge.bridge-nf-call-iptables=0
-	sysctl -w net.bridge.bridge-nf-call-ip6tables=0
-
-	sed '/net.bridge.bridge-nf-call-arptables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
-	sed '/net.bridge.bridge-nf-call-iptables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
-	sed '/net.bridge.bridge-nf-call-ip6tables=1/d' -i /etc/sysctl.d/qca-nss-ecm.conf
+  sysctl_update net.bridge.bridge-nf-call-arptables 0
+  sysctl_update net.bridge.bridge-nf-call-iptables 0
+  sysctl_update net.bridge.bridge-nf-call-ip6tables 0
 }
 
 load_ecm() {
-	[ -d /sys/module/ecm ] || {
-		insmod ecm front_end_selection=$(get_front_end_mode)
-		echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
-	}
+  [ -d /sys/module/ecm ] || {
+    insmod ecm front_end_selection="$(get_front_end_mode)"
+    echo 1 > /sys/kernel/debug/ecm/ecm_classifier_default/accel_delay_pkts
+  }
 
-	support_bridge
+  # Set conntrack event mode to 1 for 6.1 kernel to get the conntrack events from ECM
+  local kernel_major
+  kernel_major=$(uname -r |cut -d. -f1)
+  if [ "$kernel_major" -eq 6 ]; then
+    echo 1 > /proc/sys/net/netfilter/nf_conntrack_events
+  fi
 }
 
 unload_ecm() {
-	disable_bridge_filtering
+  disable_bridge_filtering
 
-	if [ -d /sys/module/ecm ]; then
-		#
-		# Stop ECM frontends
-		#
-		echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
-		echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
+  # Change it back to 6.1 linux's default setting
+  local kernel_major
+  kernel_major="$(uname -r |cut -d. -f1)"
+  if [ "$kernel_major" -eq 6 ]; then
+    echo 2 > /proc/sys/net/netfilter/nf_conntrack_events
+  fi
 
-		#
-		# Defunct the connections
-		#
-	    echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
-		sleep 5
+  if [ -d /sys/module/ecm ]; then
+    #
+    # Stop ECM frontends
+    #
+    echo 1 > /sys/kernel/debug/ecm/front_end_ipv4_stop
+    echo 1 > /sys/kernel/debug/ecm/front_end_ipv6_stop
 
-		rmmod ecm
-		sleep 1
-	fi
+    #
+    # Defunct the connections
+    #
+    echo 1 > /sys/kernel/debug/ecm/ecm_db/defunct_all
+    sleep 5
+
+    rmmod ecm
+    sleep 1
+  fi
 }
 
 start() {
-	load_ecm
+  load_ecm
 
-	# If the acceleration engine is NSS, enable wifi redirect
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=1
+  # If the acceleration engine is NSS, enable wifi redirect
+  [ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=1
 
-	# If bridge filtering is enabled, apply and persist the sysctl flags
-	local bridge_filtering_enabled="$(uci get ecm.@general[0].enable_bridge_filtering)"
-	if [ "$bridge_filtering_enabled" -eq 1 ]; then
-		echo "Bridge filtering is enabled in the ECM config, this will cause issues with NAT loopback!"
-		enable_bridge_filtering
-	else
-		disable_bridge_filtering
-	fi
+  # If bridge filtering is enabled, apply and persist the sysctl flags
+  local bridge_filtering_enabled
+  bridge_filtering_enabled="$(uci get ecm.@general[0].enable_bridge_filtering)"
+  if [ "$bridge_filtering_enabled" -eq 1 ]; then
+    echo "Bridge filtering is enabled in the ECM config, this will cause issues with NAT loopback!"
+    enable_bridge_filtering
+  else
+    disable_bridge_filtering
+  fi
 
-	if [ -d /sys/module/qca_ovsmgr ]; then
-		insmod ecm_ovs
-	fi
+  if [ -d /sys/module/qca_ovsmgr ]; then
+    insmod ecm_ovs
+  fi
 }
 
 stop() {
-	# If ECM is already not loaded, just return
-	if [ ! -d /sys/module/ecm ]; then
-		return
-	fi
+  # If ECM is already not loaded, just return
+  if [ ! -d /sys/module/ecm ]; then
+    return
+  fi
 
-	# If the acceleration engine is NSS, disable wifi redirect
-	[ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=0
+  # If the acceleration engine is NSS, disable wifi redirect
+  [ -d /sys/kernel/debug/ecm/ecm_nss_ipv4 ] && sysctl -w dev.nss.general.redirect=0
 
-	if [ -d /sys/module/ecm_ovs ]; then
-		rmmod ecm_ovs
-	fi
+  if [ -d /sys/module/ecm_ovs ]; then
+    rmmod ecm_ovs
+  fi
 
-	unload_ecm
+  unload_ecm
 }
